version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=gym_notes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    depends_on:
      - db
  db:
    image: mysql:5.7.28
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=example
