version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - /node_modules
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=gym_notes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    depends_on:
      - db
